####DON'T FORGET TO REPLACE SCHEMA AND TABLE NAME######

INSERT INTO schema.province (province_code,province_name,region) VALUES (50,'Chiang Mai',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (51,'Lamphun',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (52,'Lampang',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (54,'Phrae',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (55,'Nan',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (56,'Phayao',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (57,'Chiang Rai',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (58,'Mae Hong Son',1);
INSERT INTO schema.province (province_code,province_name,region) VALUES (53,'Uttaradit',2);
INSERT INTO schema.province (province_code,province_name,region) VALUES (63,'Tak',2);
INSERT INTO schema.province (province_code,province_name,region) VALUES (64,'Sukhothai',2);
INSERT INTO schema.province (province_code,province_name,region) VALUES (65,'Phitsanulok',2);
INSERT INTO schema.province (province_code,province_name,region) VALUES (67,'Phetchabun',2);
INSERT INTO schema.province (province_code,province_name,region) VALUES (60,'Nakohn Sawan',3);
INSERT INTO schema.province (province_code,province_name,region) VALUES (61,'Uthai Thani',3);
INSERT INTO schema.province (province_code,province_name,region) VALUES (62,'Kamphaeng Phet',3);
INSERT INTO schema.province (province_code,province_name,region) VALUES (66,'Phichit',3);
INSERT INTO schema.province (province_code,province_name,region) VALUES (18,'Chai Nat',3);
INSERT INTO schema.province (province_code,province_name,region) VALUES (12,'Nonthaburi',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (13,'Pathum Thani',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (14,'Phra Nakhon Si Ayutthaya',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (15,'Ang Thong',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (16,'Lopburi',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (17,'Sing Buri',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (19,'Saraburi',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (26,'Nakhon Nayok',4);
INSERT INTO schema.province (province_code,province_name,region) VALUES (70,'Ratchaburi',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (71,'Kanchanaburi',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (72,'Suphan Buri',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (73,'Nakhon Pathom',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (74,'Samut Sakhon',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (75,'Samut Songkhram',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (76,'Phetchaburi',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (77,'Prachuap Khiri Khan',5);
INSERT INTO schema.province (province_code,province_name,region) VALUES (11,'Samut Prakan',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (20,'Chonburi',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (21,'Rayong',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (22,'Chanthaburi',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (23,'Trat',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (24,'Chachoengsao',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (25,'Prachinburi',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (27,'Sa Kaeo',6);
INSERT INTO schema.province (province_code,province_name,region) VALUES (40,'Khon Kaen',7);
INSERT INTO schema.province (province_code,province_name,region) VALUES (44,'Maha Sarakham',7);
INSERT INTO schema.province (province_code,province_name,region) VALUES (45,'Roi Et',7);
INSERT INTO schema.province (province_code,province_name,region) VALUES (46,'Kalasin',7);
INSERT INTO schema.province (province_code,province_name,region) VALUES (38,'Bueng Kan',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (39,'Nong Bua Lam Phu',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (41,'Udon Thani',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (42,'Loei',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (43,'Nong Khai',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (47,'akon Nakhon',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (48,'Nakhon Phanom',8);
INSERT INTO schema.province (province_code,province_name,region) VALUES (30,'Nakhon Ratchasima',9);
INSERT INTO schema.province (province_code,province_name,region) VALUES (31,'Buriram',9);
INSERT INTO schema.province (province_code,province_name,region) VALUES (32,'Surin',9);
INSERT INTO schema.province (province_code,province_name,region) VALUES (36,'Chaiyaphum',9);
INSERT INTO schema.province (province_code,province_name,region) VALUES (33,'Sisaket',10);
INSERT INTO schema.province (province_code,province_name,region) VALUES (34,'Ubon Ratchathani',10);
INSERT INTO schema.province (province_code,province_name,region) VALUES (35,'Yasothon',10);
INSERT INTO schema.province (province_code,province_name,region) VALUES (37,'Amnat Charoen',10);
INSERT INTO schema.province (province_code,province_name,region) VALUES (49,'Mukdahan',10);
INSERT INTO schema.province (province_code,province_name,region) VALUES (80,'Nakhon Si Thammarat',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (81,'Krabi',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (82,'Phang Nga',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (83,'Phuket',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (84,'Surat Thani',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (85,'Ranong',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (86,'Chumphon',11);
INSERT INTO schema.province (province_code,province_name,region) VALUES (90,'Songkhla',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (91,'Satun',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (92,'Trang',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (93,'Phatthalung',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (94,'Pattani',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (95,'Yala',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (96,'Narathiwat',12);
INSERT INTO schema.province (province_code,province_name,region) VALUES (10,'Bangkok',13);
